name: update-stats
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.6'
      
      - name: Install go-readme-stats
        run: go install github.com/Sawawa42/go-readme-stats/cmd@latest
      
      - name: Generate stats
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_GITHUB_TOKEN }}
        run: cmd -x=Kotlin

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./generated/language-stats.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update language stats SVG [automated]"
            git push
          fi
